@startuml classdiagram

class Users {
  +ID : int
  +firstName : string
  +lastName : string
  +Login : string
  +Password : string
}

class Colors {
  +ID : int
  +Name : string
  +UserID : int
}

Users --> Colors : owns

@enduml